---
- name: configure the apache2 on Ubuntu and httpd on RHEL servers
  hosts: all
  tasks:
    - name: install apache2 on Ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install httpd on RHEL servers
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: edit the index.html file
      copy:
        content: "welcome to intelliqit"
        dest: /var/www/html/index.html
    - name: restart apache2 on Ubuntu servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: restart httpd on RHEL servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: check apache/httpd response on all managed nodes
      uri:
        url: "{{item}}"
        status_code: 200
      with_items: 
         - http://172.31.20.87
         - http://172.31.28.165
         - http://172.31.29.241
...
