---
 - name: install/uninstall s/w packages
   hosts: all
   vars:
     - a: tomcat9
     - b: present
     - c: yes
   tasks:
     - name: install/uninstall
       apt:
          name: "{{a}}"
          state: "{{b}}"
          update_cache: "{{c}}"
