---
- name: capture OS info
  hosts: all
  tasks:
    - name: capture OS name
      debug:
        msg: "{{ansible_distribution}}"
    - name: capture the OS version
      debug:
        msg: "{{ansible_distribution_version}}"
    - name: capture major version no
      debug:
        msg: "{{ansible_distribution_major_version}}"
